name: Dividex
description: "DACN - 251"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  device_info_plus: ^10.1.0
  package_info_plus: ^8.3.0
  geolocator: ^10.1.0

  http: ^1.4.0
  web_socket_channel: ^2.4.0

  flutter_launcher_icons: ^0.14.4

  # UI & Icons
  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^9.1.1
  provider: ^6.0.5
  equatable: ^2.0.5

  # Routing
  go_router: ^15.1.3
  go_router_builder: ^3.2.1

  # Localization
  intl: ^0.20.2
  flutter_localized_locales: ^2.0.5

  # Storage & Environment Config
  shared_preferences: ^2.5.3
  flutter_dotenv: ^5.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11

  # Networking & JSON Handling
  dio: ^5.0.0
  retrofit: ^4.0.1
  json_annotation: ^4.9.0

  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.4.1

  # Logging
  logger: ^2.0.2

  # Notifications
  firebase_core: ^2.31.0
  firebase_messaging: ^14.9.1
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.0
  awesome_notifications: ^0.10.1

  # Image Picker
  image_picker: ^1.1.2
  flutter_otp_text_field: ^1.5.1+1
  flutter_image_compress: ^2.3.0
  flutter_svg: ^2.2.0
  jwt_decoder: ^2.0.1
  image_cropper: ^9.1.0
  video_thumbnail: ^0.5.6
  video_player: ^2.10.0
  chewie: ^1.12.1
  mime: ^2.0.0
  http_parser: ^4.1.2
  flutter_slidable: ^4.0.0
  timeago: ^3.7.1
  google_sign_in: ^7.1.1
  url_launcher: ^6.3.2
  marquee: ^2.3.0
  
  google_fonts: ^6.2.1
  file_picker: ^8.0.7
  image_editor_plus: ^1.0.6
  flutter_spinkit: ^5.2.2
  animations: ^2.0.11
  fl_chart: ^1.1.1
  webview_flutter: ^4.13.0
  flutter_native_splash: ^2.4.7
  vietqr_core: ^0.2.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.24.0
  hive_test: ^1.0.0
  analyzer: ^7.4.0

  # Code Generation
  build_runner: ^2.4.6
  json_serializable: ^6.6.1
  retrofit_generator: ^10.0.2
  injectable_generator: ^2.4.1
  intl_utils: ^2.8.2

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/Logo.png"

flutter_native_splash:
  color: "#FFFFFF"
  android: true
  ios: true
  web: true
  image: lib/assets/images/Logo.png 

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - lib/assets/images/
    - lib/assets/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: lib/assets/fonts/FZ-Poppins-Regular.ttf
        - asset: lib/assets/fonts/FZ-Poppins-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/FZ-Poppins-Bold.ttf
          weight: 700

